/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pmis;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class POSMRegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form POSMRegistrationForm
     */
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public POSMRegistrationForm() throws SQLException {
        initComponents();
        con = DbConnection.ConnectionDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        emailTxtbx = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JPasswordField();
        confPasswordTxt = new javax.swing.JPasswordField();
        registerBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(12, 18, 66));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Register");

        emailTxtbx.setText("Email");
        emailTxtbx.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTxtbxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTxtbxFocusLost(evt);
            }
        });

        passwordTxt.setText("Password");
        passwordTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTxtFocusLost(evt);
            }
        });

        confPasswordTxt.setText("Confirm Password");
        confPasswordTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confPasswordTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confPasswordTxtFocusLost(evt);
            }
        });
        confPasswordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confPasswordTxtActionPerformed(evt);
            }
        });

        registerBtn.setBackground(new java.awt.Color(12, 18, 66));
        registerBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerBtn.setText("Register");
        registerBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailTxtbx)
                    .addComponent(passwordTxt)
                    .addComponent(confPasswordTxt)
                    .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(162, 162, 162))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(emailTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ASP-LOGO-FINAL 1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1296, 772));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    String emailPlaceHolder = "Email";
    String passPlaceHolder = "Password";
    String confPassPlaceHolder = "Confirm Password";
    private void emailTxtbxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTxtbxFocusGained
        // TODO add your handling code here:
        if (emailTxtbx.getText().equals(emailPlaceHolder)){
            emailTxtbx.setText("");
            emailTxtbx.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_emailTxtbxFocusGained

    private void emailTxtbxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTxtbxFocusLost
        // TODO add your handling code here:
        if (emailTxtbx.getText().equals("")){
            emailTxtbx.setText(emailPlaceHolder);
            emailTxtbx.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_emailTxtbxFocusLost

    private void passwordTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTxtFocusGained
        // TODO add your handling code here:
        if (new String(passwordTxt.getPassword()).equals(passPlaceHolder)) {
            passwordTxt.setText("");
            passwordTxt.setForeground(Color.GRAY);
            passwordTxt.setEchoChar('*');  // Enable masking after focus
        }
    }//GEN-LAST:event_passwordTxtFocusGained

    private void passwordTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTxtFocusLost
        // TODO add your handling code here:
        if (new String(passwordTxt.getPassword()).equals("")) {
            passwordTxt.setText(passPlaceHolder);
            passwordTxt.setForeground(Color.GRAY);
            passwordTxt.setEchoChar((char) 0);  // Enable masking after focus
        }
    }//GEN-LAST:event_passwordTxtFocusLost

    private void confPasswordTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confPasswordTxtFocusGained
        // TODO add your handling code here:
        if (new String(confPasswordTxt.getPassword()).equals(confPassPlaceHolder)) {
            confPasswordTxt.setText("");
            confPasswordTxt.setForeground(Color.GRAY);
            confPasswordTxt.setEchoChar('*');  // Disable masking when placeholder is visible
        }
    }//GEN-LAST:event_confPasswordTxtFocusGained

    private void confPasswordTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confPasswordTxtFocusLost
        // TODO add your handling code here:
        if (new String(confPasswordTxt.getPassword()).equals("")) {
            confPasswordTxt.setText(confPassPlaceHolder);
            confPasswordTxt.setForeground(Color.GRAY);
            confPasswordTxt.setEchoChar((char) 0);  // Disable masking when placeholder is visible
        }
    }//GEN-LAST:event_confPasswordTxtFocusLost

    private void confPasswordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confPasswordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confPasswordTxtActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        String txtEmail = emailTxtbx.getText();
        String txtPassword = passwordTxt.getText();
        String txtConfPass = confPasswordTxt.getText();
        String query = "INSERT INTO POSMAcc (Email, Password) VALUES (?, ?);";

        if (txtPassword.equals(txtConfPass)) {
            try {
                pst = con.prepareStatement(query);
                pst.setString(1, txtEmail);
                pst.setString(2, txtPassword);
                int insert = pst.executeUpdate();

                if (insert > 0){
                    JOptionPane.showMessageDialog(null, "Registration Successful");
                }
                else {
                    JOptionPane.showMessageDialog(null, "Failed");
                }

                POSMLoginForm posMLoginForm = new POSMLoginForm();
                posMLoginForm.setVisible(true);
                dispose();
            }
            catch (Exception e){

            }
        }
        else {
            System.out.println("mali");
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POSMRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POSMRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POSMRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POSMRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new POSMRegistrationForm().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(POSMRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confPasswordTxt;
    private javax.swing.JTextField emailTxtbx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JButton registerBtn;
    // End of variables declaration//GEN-END:variables
}
