/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import pmis.EditProducts;

/**
 *
 * @author Dell
 */
public class inventoryItem extends javax.swing.JPanel {

    /**
     * Creates new form inventoryItem
     */
    
    private int productID;

    // Fetch productID
    public int getProductID() {
        return productID;
    }

    // Set productID (this could be called when fetching from DB or user selection)
    public void setProductID(int id) {
        this.productID = id;
    }
    
    public inventoryItem() {
        initComponents();
    }
    
    public void setProductData(String productName, int productID, String productType, double price, int stocks, 
                           String deliveryDate, String manufacturedDate, String expirationDate) {
        this.setProductID(productID); 
        productNameLbl.setText(productName);
        productIDLbl.setText("Product ID: " + productID);
        productTypeLbl.setText("Product Type: " + productType);
        priceLbl.setText("Price: ₱" + price);
        stocksLbl.setText("Stocks: " + stocks);

        // Safely display dates, show "N/A" if any date is null
        deliveryDateLbl.setText("Delivery Date: " + (deliveryDate != null ? deliveryDate : "N/A"));
        manufacturedDateLbl.setText("Manufactured Date: " + (manufacturedDate != null ? manufacturedDate : "N/A"));
        expirationDateLbl.setText("Expiration Date: " + (expirationDate != null ? expirationDate : "N/A"));
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productNameLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        productIDLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        productTypeLbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        priceLbl = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        stocksLbl = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        deliveryDateLbl = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        manufacturedDateLbl = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        expirationDateLbl = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setForeground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productNameLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productNameLbl.setForeground(new java.awt.Color(0, 0, 0));
        productNameLbl.setText("Product Name");
        add(productNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 193, -1));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 1));
        jPanel1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 35, 193, -1));

        productIDLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        productIDLbl.setForeground(new java.awt.Color(0, 0, 0));
        productIDLbl.setText("Product ID:");
        add(productIDLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 43, 193, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 1));
        jPanel2.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 65, 193, -1));

        productTypeLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        productTypeLbl.setForeground(new java.awt.Color(0, 0, 0));
        productTypeLbl.setText("Product Type:");
        add(productTypeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 73, 193, -1));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 1));
        jPanel3.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 95, 193, -1));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 1));
        jPanel4.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 125, 193, -1));

        priceLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        priceLbl.setForeground(new java.awt.Color(0, 0, 0));
        priceLbl.setText("Price:");
        add(priceLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 103, 193, -1));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 1));
        jPanel5.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 150, 193, -1));

        stocksLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        stocksLbl.setForeground(new java.awt.Color(0, 0, 0));
        stocksLbl.setText("Stocks:");
        add(stocksLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 128, 193, -1));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 1));
        jPanel6.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 180, 193, -1));

        deliveryDateLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deliveryDateLbl.setForeground(new java.awt.Color(0, 0, 0));
        deliveryDateLbl.setText("Delivery Date:");
        add(deliveryDateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 158, 193, -1));

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));
        jPanel7.setPreferredSize(new java.awt.Dimension(100, 1));
        jPanel7.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 210, 193, -1));

        manufacturedDateLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        manufacturedDateLbl.setForeground(new java.awt.Color(0, 0, 0));
        manufacturedDateLbl.setText("Manufactured Date:");
        add(manufacturedDateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 188, 193, -1));

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel8.setPreferredSize(new java.awt.Dimension(100, 1));
        jPanel8.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 240, 193, -1));

        expirationDateLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        expirationDateLbl.setForeground(new java.awt.Color(0, 0, 0));
        expirationDateLbl.setText("Expiration Date:");
        add(expirationDateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 218, 193, -1));

        editBtn.setBackground(new java.awt.Color(255, 255, 255));
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit_1.png"))); // NOI18N
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 20, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
         int productID = getProductID(); // Fetch productID
    System.out.println("Product ID being sent to EditProducts: " + productID); // Debug print

    if (productID == 0) {
        JOptionPane.showMessageDialog(this, "Error: Product ID not set.");
        return; // Stop execution if productID is not set
    }

    EditProducts editProducts = new EditProducts();
    editProducts.setProductID(productID);
    editProducts.loadProductDetails(); // Load product details
    editProducts.setVisible(true);
        
    }//GEN-LAST:event_editBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deliveryDateLbl;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel expirationDateLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel manufacturedDateLbl;
    private javax.swing.JLabel priceLbl;
    private javax.swing.JLabel productIDLbl;
    private javax.swing.JLabel productNameLbl;
    private javax.swing.JLabel productTypeLbl;
    private javax.swing.JLabel stocksLbl;
    // End of variables declaration//GEN-END:variables
}
