/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

/**
 *
 * @author Dell
 */
public class MostSellingProduct extends javax.swing.JPanel {

    /**
     * Creates new form MostSellingProduct
     */
    public MostSellingProduct() {
        initComponents();
    }

    public void setProductData(String productName, int quantitySold) {
        productNameLbl.setText("<html>" + productName + "</html>");
        quantitySoldLbl.setText("<html>Sold: " + quantitySold + "</html>");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productNameLbl = new javax.swing.JLabel();
        quantitySoldLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(238, 70));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productNameLbl.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        productNameLbl.setForeground(new java.awt.Color(51, 51, 51));
        productNameLbl.setText("Product");
        productNameLbl.setToolTipText("");
        add(productNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 26, -1, -1));

        quantitySoldLbl.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        quantitySoldLbl.setForeground(new java.awt.Color(51, 51, 51));
        quantitySoldLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        quantitySoldLbl.setText("Number");
        add(quantitySoldLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 26, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel productNameLbl;
    private javax.swing.JLabel quantitySoldLbl;
    // End of variables declaration//GEN-END:variables
}
